let currentUser=null;const $=id=>document.getElementById(id);
$("signInBtn").onclick=login;$("logoutBtn").onclick=logout;
async function login(){const email=$("email").value.trim(),password=$("password").value;if(!email||!password){$("loginMessage").textContent="Enter email and password.";return}const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){$("loginMessage").textContent=error.message;return}currentUser=data.user;showDashboard();refreshAll()}
async function logout(){await supabaseClient.auth.signOut();location.reload()}
function showDashboard(){$("loginScreen").style.display="none";$("dashboard").style.display="block";$("loggedInEmail").textContent=currentUser.email}
async function checkSession(){const {data}=await supabaseClient.auth.getUser();if(data.user){currentUser=data.user;showDashboard();refreshAll()}}
async function refreshAll(){loadProfile();loadAchievements();loadPosts();loadGallery()}
async function loadProfile(){const {data}=await supabaseClient.from("profiles").select("*").eq("id",currentUser.id).maybeSingle();if(!data)return;$("fullName").value=data.full_name||data.name||"";$("profession").value=data.professional_title||data.profession||"";$("bio").value=data.bio||"";$("yearsExperience").value=data.years_experience||"";$("contactEmail").value=data.contact_email||"";if(data.profile_photo)$("profilePreview").src=data.profile_photo}
$("saveProfileBtn").onclick=async()=>{let photo=null;const f=$("profilePhoto").files[0];if(f){const r=await uploadImage(f,"profiles");photo=r}const {data:old}=await supabaseClient.from("profiles").select("profile_photo").eq("id",currentUser.id).maybeSingle();const {error}=await supabaseClient.from("profiles").upsert({id:currentUser.id,full_name:$("fullName").value.trim(),professional_title:$("profession").value.trim(),bio:$("bio").value.trim(),years_experience:$("yearsExperience").value.trim(),contact_email:$("contactEmail").value.trim(),profile_photo:photo||old?.profile_photo||null,updated_at:new Date().toISOString()});$("profileMessage").textContent=error?error.message:"Profile saved."}
$("addAchievementBtn").onclick=async()=>{const {error}=await supabaseClient.from("achievements").insert({title:$("achievementTitle").value.trim(),year:$("achievementYear").value.trim(),description:$("achievementDescription").value.trim()});$("achievementMessage").textContent=error?error.message:"Achievement added.";if(!error){$("achievementTitle").value="";$("achievementYear").value="";$("achievementDescription").value="";loadAchievements()}}
async function loadAchievements(){const {data,error}=await supabaseClient.from("achievements").select("*").order("year",{ascending:false});if(error)return;const l=$("achievementsList");l.innerHTML=data?.length?"":"<p>No achievements.</p>";(data||[]).forEach(a=>{const d=document.createElement("div");d.className="manage";d.innerHTML=`<div><strong>${esc(a.title)}</strong><small>${esc(String(a.year||""))}</small><p>${esc(a.description||"")}</p></div><div class="actions"><button onclick="editAchievement('${a.id}')">Edit</button><button class="danger" onclick="deleteAchievement('${a.id}')">Delete</button></div>`;l.appendChild(d)})}
async function editAchievement(id){const {data}=await supabaseClient.from("achievements").select("*").eq("id",id).single();const title=prompt("Title:",data.title||"");if(title===null)return;const year=prompt("Year:",data.year||"");if(year===null)return;const description=prompt("Description:",data.description||"");if(description===null)return;const {error}=await supabaseClient.from("achievements").update({title,year,description}).eq("id",id);if(error)alert(error.message);else loadAchievements()}
async function deleteAchievement(id){if(!confirm("Delete this achievement permanently?"))return;const {error}=await supabaseClient.from("achievements").delete().eq("id",id);if(error)alert(error.message);else loadAchievements()}
$("publishPostBtn").onclick=async()=>{let image_url=null;const f=$("postImage").files[0];if(f)image_url=await uploadImage(f,"posts");const {error}=await supabaseClient.from("posts").insert({title:$("postTitle").value.trim(),category:$("postCategory").value.trim()||"Story",content:$("postContent").value.trim(),image_url,published:true});$("postMessage").textContent=error?error.message:"Post published.";if(!error)loadPosts()}
async function loadPosts(){const {data,error}=await supabaseClient.from("posts").select("*").order("created_at",{ascending:false});if(error)return;const l=$("postsList");l.innerHTML=data?.length?"":"<p>No posts.</p>";(data||[]).forEach(p=>{const d=document.createElement("div");d.className="manage";d.innerHTML=`<div><strong>${esc(p.title)}</strong><small>${esc(p.category||"Story")} · ${p.published?"Published":"Hidden"}</small><p>${esc(p.content||"")}</p></div><div class="actions"><button onclick="editPost('${p.id}')">Edit</button><button onclick="togglePost('${p.id}',${!p.published})">${p.published?"Hide":"Publish"}</button><button class="danger" onclick="deletePost('${p.id}')">Delete</button></div>`;l.appendChild(d)})}
async function editPost(id){const {data}=await supabaseClient.from("posts").select("*").eq("id",id).single();const title=prompt("Title:",data.title||"");if(title===null)return;const category=prompt("Category:",data.category||"Story");if(category===null)return;const content=prompt("Content:",data.content||"");if(content===null)return;const {error}=await supabaseClient.from("posts").update({title,category,content}).eq("id",id);if(error)alert(error.message);else loadPosts()}
async function togglePost(id,published){const {error}=await supabaseClient.from("posts").update({published}).eq("id",id);if(error)alert(error.message);else loadPosts()}
async function deletePost(id){if(!confirm("Delete this post permanently?"))return;const {error}=await supabaseClient.from("posts").delete().eq("id",id);if(error)alert(error.message);else loadPosts()}
$("uploadGalleryBtn").onclick=async()=>{for(const f of $("galleryFiles").files){const url=await uploadImage(f,"gallery");await supabaseClient.from("gallery").insert({image_url:url,caption:f.name})}$("galleryMessage").textContent="Photos uploaded.";loadGallery()}
async function loadGallery(){const {data,error}=await supabaseClient.from("gallery").select("*").order("created_at",{ascending:false});if(error)return;const l=$("galleryList");l.innerHTML=data?.length?"":"<p>No gallery items.</p>";(data||[]).forEach(g=>{const d=document.createElement("div");d.className="manage";d.innerHTML=`<div class="gallery-item"><img src="${attr(g.image_url)}"><strong>${esc(g.caption||"Gallery image")}</strong></div><div class="actions"><button onclick="editGallery('${g.id}')">Edit</button><button class="danger" onclick="deleteGallery('${g.id}')">Delete</button></div>`;l.appendChild(d)})}
async function editGallery(id){const {data}=await supabaseClient.from("gallery").select("*").eq("id",id).single();const caption=prompt("Caption:",data.caption||"");if(caption===null)return;const {error}=await supabaseClient.from("gallery").update({caption}).eq("id",id);if(error)alert(error.message);else loadGallery()}
async function deleteGallery(id){if(!confirm("Delete this gallery item permanently?"))return;const {error}=await supabaseClient.from("gallery").delete().eq("id",id);if(error)alert(error.message);else loadGallery()}
async function uploadImage(file,folder){const ext=file.name.split(".").pop().toLowerCase();const path=`${folder}/${currentUser.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await supabaseClient.storage.from("portfolio-images").upload(path,file);if(error)throw error;return supabaseClient.storage.from("portfolio-images").getPublicUrl(path).data.publicUrl}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function attr(v=""){return String(v).replace(/["']/g,c=>c==='"'?"&quot;":"&#039;")}
checkSession();
